/**
 * Templates API - 100+ Templates
 *
 * GET /api/templates - List all available templates
 * Supports filtering by category, style, and search
 *
 * CATEGORIES: 15 event types
 * TEMPLATES: 100+ unique designs
 */

import { NextRequest, NextResponse } from "next/server";

// Template data - comprehensive library of 100+ templates
const TEMPLATES = [
  // ==========================================
  // WEDDING TEMPLATES (15)
  // ==========================================
  {
    id: "wedding-elegant-floral",
    name: "Elegant Floral",
    category: "wedding",
    style: "elegant",
    thumbnail: "/templates/wedding/elegant-floral.jpg",
    premium: false,
    colors: ["#D4AF37", "#1C1917", "#FAFAF9"],
    fonts: ["Playfair Display", "Source Serif Pro"],
    popularity: 98,
    createdAt: "2024-01-15",
  },
  {
    id: "wedding-modern-minimal",
    name: "Modern Minimal",
    category: "wedding",
    style: "minimalist",
    thumbnail: "/templates/wedding/modern-minimal.jpg",
    premium: false,
    colors: ["#18181B", "#71717A", "#FFFFFF"],
    fonts: ["Outfit", "Inter"],
    popularity: 95,
    createdAt: "2024-02-01",
  },
  {
    id: "wedding-rustic-charm",
    name: "Rustic Charm",
    category: "wedding",
    style: "rustic",
    thumbnail: "/templates/wedding/rustic-charm.jpg",
    premium: true,
    colors: ["#44403C", "#A8A29E", "#D6D3D1"],
    fonts: ["Cormorant Garamond", "Montserrat"],
    popularity: 92,
    createdAt: "2024-02-15",
  },
  {
    id: "wedding-garden-romance",
    name: "Garden Romance",
    category: "wedding",
    style: "romantic",
    thumbnail: "/templates/wedding/garden-romance.jpg",
    premium: true,
    colors: ["#14532D", "#22C55E", "#F0FDF4"],
    fonts: ["Playfair Display", "Nunito"],
    popularity: 89,
    createdAt: "2024-03-01",
  },
  {
    id: "wedding-vintage-gold",
    name: "Vintage Gold",
    category: "wedding",
    style: "vintage",
    thumbnail: "/templates/wedding/vintage-gold.jpg",
    premium: true,
    colors: ["#78350F", "#D4AF37", "#FEF3C7"],
    fonts: ["Cormorant Garamond", "EB Garamond"],
    popularity: 87,
    createdAt: "2024-03-10",
  },
  {
    id: "wedding-beach-destination",
    name: "Beach Destination",
    category: "wedding",
    style: "tropical",
    thumbnail: "/templates/wedding/beach-destination.jpg",
    premium: false,
    colors: ["#0891B2", "#67E8F9", "#ECFEFF"],
    fonts: ["Outfit", "DM Sans"],
    popularity: 85,
    createdAt: "2024-03-15",
  },
  {
    id: "wedding-bohemian-dream",
    name: "Bohemian Dream",
    category: "wedding",
    style: "bohemian",
    thumbnail: "/templates/wedding/bohemian-dream.jpg",
    premium: true,
    colors: ["#B45309", "#FBBF24", "#FEF3C7"],
    fonts: ["Amatic SC", "Josefin Sans"],
    popularity: 84,
    createdAt: "2024-03-20",
  },
  {
    id: "wedding-classic-navy",
    name: "Classic Navy",
    category: "wedding",
    style: "classic",
    thumbnail: "/templates/wedding/classic-navy.jpg",
    premium: false,
    colors: ["#1E3A8A", "#D4AF37", "#FFFFFF"],
    fonts: ["Playfair Display", "Lora"],
    popularity: 83,
    createdAt: "2024-04-01",
  },
  {
    id: "wedding-watercolor-blush",
    name: "Watercolor Blush",
    category: "wedding",
    style: "artistic",
    thumbnail: "/templates/wedding/watercolor-blush.jpg",
    premium: true,
    colors: ["#DB2777", "#FBCFE8", "#FDF2F8"],
    fonts: ["Dancing Script", "Quicksand"],
    popularity: 82,
    createdAt: "2024-04-10",
  },
  {
    id: "wedding-art-deco",
    name: "Art Deco Glamour",
    category: "wedding",
    style: "art-deco",
    thumbnail: "/templates/wedding/art-deco.jpg",
    premium: true,
    colors: ["#18181B", "#D4AF37", "#FAFAF9"],
    fonts: ["Poiret One", "Raleway"],
    popularity: 81,
    createdAt: "2024-04-15",
  },
  {
    id: "wedding-lavender-fields",
    name: "Lavender Fields",
    category: "wedding",
    style: "romantic",
    thumbnail: "/templates/wedding/lavender-fields.jpg",
    premium: false,
    colors: ["#7C3AED", "#DDD6FE", "#F5F3FF"],
    fonts: ["Playfair Display", "Lato"],
    popularity: 80,
    createdAt: "2024-04-20",
  },
  {
    id: "wedding-autumn-harvest",
    name: "Autumn Harvest",
    category: "wedding",
    style: "rustic",
    thumbnail: "/templates/wedding/autumn-harvest.jpg",
    premium: false,
    colors: ["#C2410C", "#FB923C", "#FFF7ED"],
    fonts: ["Merriweather", "Open Sans"],
    popularity: 79,
    createdAt: "2024-05-01",
  },
  {
    id: "wedding-winter-wonderland",
    name: "Winter Wonderland",
    category: "wedding",
    style: "elegant",
    thumbnail: "/templates/wedding/winter-wonderland.jpg",
    premium: true,
    colors: ["#164E63", "#A5F3FC", "#ECFEFF"],
    fonts: ["Cormorant Garamond", "Montserrat"],
    popularity: 78,
    createdAt: "2024-05-10",
  },
  {
    id: "wedding-tropical-paradise",
    name: "Tropical Paradise",
    category: "wedding",
    style: "tropical",
    thumbnail: "/templates/wedding/tropical-paradise.jpg",
    premium: false,
    colors: ["#059669", "#34D399", "#D1FAE5"],
    fonts: ["Pacifico", "Poppins"],
    popularity: 77,
    createdAt: "2024-05-15",
  },
  {
    id: "wedding-celestial-night",
    name: "Celestial Night",
    category: "wedding",
    style: "modern",
    thumbnail: "/templates/wedding/celestial-night.jpg",
    premium: true,
    colors: ["#312E81", "#818CF8", "#E0E7FF"],
    fonts: ["Cinzel", "Lato"],
    popularity: 76,
    createdAt: "2024-05-20",
  },

  // ==========================================
  // BIRTHDAY TEMPLATES (12)
  // ==========================================
  {
    id: "birthday-confetti-blast",
    name: "Confetti Blast",
    category: "birthday",
    style: "playful",
    thumbnail: "/templates/birthday/confetti-blast.jpg",
    premium: false,
    colors: ["#FF6B47", "#14B8A6", "#FBBF24"],
    fonts: ["Fredoka One", "Nunito"],
    popularity: 97,
    createdAt: "2024-01-20",
  },
  {
    id: "birthday-neon-glow",
    name: "Neon Glow",
    category: "birthday",
    style: "bold",
    thumbnail: "/templates/birthday/neon-glow.jpg",
    premium: false,
    colors: ["#8B5CF6", "#EC4899", "#06B6D4"],
    fonts: ["Bebas Neue", "Open Sans"],
    popularity: 94,
    createdAt: "2024-02-10",
  },
  {
    id: "birthday-kids-fun",
    name: "Kids Fun Party",
    category: "birthday",
    style: "playful",
    thumbnail: "/templates/birthday/kids-fun.jpg",
    premium: false,
    colors: ["#EF4444", "#22C55E", "#3B82F6"],
    fonts: ["Fredoka One", "Nunito"],
    popularity: 93,
    createdAt: "2024-02-20",
  },
  {
    id: "birthday-elegant-adult",
    name: "Elegant Celebration",
    category: "birthday",
    style: "elegant",
    thumbnail: "/templates/birthday/elegant-adult.jpg",
    premium: true,
    colors: ["#D4AF37", "#1C1917", "#FAFAF9"],
    fonts: ["Playfair Display", "Inter"],
    popularity: 88,
    createdAt: "2024-03-05",
  },
  {
    id: "birthday-rainbow-party",
    name: "Rainbow Party",
    category: "birthday",
    style: "colorful",
    thumbnail: "/templates/birthday/rainbow-party.jpg",
    premium: false,
    colors: ["#EF4444", "#F59E0B", "#10B981", "#3B82F6", "#8B5CF6"],
    fonts: ["Bubblegum Sans", "Comic Neue"],
    popularity: 91,
    createdAt: "2024-03-15",
  },
  {
    id: "birthday-princess-castle",
    name: "Princess Castle",
    category: "birthday",
    style: "themed",
    thumbnail: "/templates/birthday/princess-castle.jpg",
    premium: true,
    colors: ["#EC4899", "#F9A8D4", "#FDF2F8"],
    fonts: ["Princess Sofia", "Quicksand"],
    popularity: 89,
    createdAt: "2024-03-20",
  },
  {
    id: "birthday-superhero",
    name: "Superhero Adventure",
    category: "birthday",
    style: "themed",
    thumbnail: "/templates/birthday/superhero.jpg",
    premium: true,
    colors: ["#DC2626", "#1D4ED8", "#FBBF24"],
    fonts: ["Bangers", "Roboto"],
    popularity: 87,
    createdAt: "2024-04-01",
  },
  {
    id: "birthday-safari-jungle",
    name: "Safari Jungle",
    category: "birthday",
    style: "themed",
    thumbnail: "/templates/birthday/safari-jungle.jpg",
    premium: false,
    colors: ["#166534", "#A16207", "#FEF3C7"],
    fonts: ["Luckiest Guy", "Nunito"],
    popularity: 86,
    createdAt: "2024-04-10",
  },
  {
    id: "birthday-unicorn-magic",
    name: "Unicorn Magic",
    category: "birthday",
    style: "whimsical",
    thumbnail: "/templates/birthday/unicorn-magic.jpg",
    premium: true,
    colors: ["#A855F7", "#F472B6", "#67E8F9"],
    fonts: ["Pacifico", "Poppins"],
    popularity: 90,
    createdAt: "2024-04-15",
  },
  {
    id: "birthday-sports-champ",
    name: "Sports Champion",
    category: "birthday",
    style: "sporty",
    thumbnail: "/templates/birthday/sports-champ.jpg",
    premium: false,
    colors: ["#16A34A", "#1D4ED8", "#FFFFFF"],
    fonts: ["Oswald", "Roboto"],
    popularity: 82,
    createdAt: "2024-04-20",
  },
  {
    id: "birthday-milestone-50",
    name: "Golden Milestone",
    category: "birthday",
    style: "elegant",
    thumbnail: "/templates/birthday/milestone-50.jpg",
    premium: true,
    colors: ["#D4AF37", "#18181B", "#FAFAF9"],
    fonts: ["Cinzel", "Lato"],
    popularity: 85,
    createdAt: "2024-05-01",
  },
  {
    id: "birthday-retro-80s",
    name: "Retro 80s",
    category: "birthday",
    style: "retro",
    thumbnail: "/templates/birthday/retro-80s.jpg",
    premium: false,
    colors: ["#F472B6", "#38BDF8", "#A3E635"],
    fonts: ["Press Start 2P", "VT323"],
    popularity: 81,
    createdAt: "2024-05-10",
  },

  // ==========================================
  // BABY SHOWER TEMPLATES (10)
  // ==========================================
  {
    id: "baby-shower-sweet-dreams",
    name: "Sweet Dreams",
    category: "baby_shower",
    style: "soft",
    thumbnail: "/templates/baby-shower/sweet-dreams.jpg",
    premium: false,
    colors: ["#FBCFE8", "#F0FDF4", "#FEF3C7"],
    fonts: ["DM Sans", "Nunito"],
    popularity: 96,
    createdAt: "2024-01-25",
  },
  {
    id: "baby-shower-woodland",
    name: "Woodland Friends",
    category: "baby_shower",
    style: "whimsical",
    thumbnail: "/templates/baby-shower/woodland.jpg",
    premium: true,
    colors: ["#14532D", "#A16207", "#FEF3C7"],
    fonts: ["Fredoka One", "DM Sans"],
    popularity: 92,
    createdAt: "2024-02-25",
  },
  {
    id: "baby-shower-modern-geo",
    name: "Modern Geometric",
    category: "baby_shower",
    style: "modern",
    thumbnail: "/templates/baby-shower/modern-geo.jpg",
    premium: false,
    colors: ["#0EA5E9", "#F97316", "#FAFAF9"],
    fonts: ["Outfit", "Inter"],
    popularity: 88,
    createdAt: "2024-03-10",
  },
  {
    id: "baby-shower-twinkle-star",
    name: "Twinkle Little Star",
    category: "baby_shower",
    style: "whimsical",
    thumbnail: "/templates/baby-shower/twinkle-star.jpg",
    premium: true,
    colors: ["#1E3A8A", "#FCD34D", "#FAFAF9"],
    fonts: ["Pacifico", "Quicksand"],
    popularity: 91,
    createdAt: "2024-03-15",
  },
  {
    id: "baby-shower-elephant-parade",
    name: "Elephant Parade",
    category: "baby_shower",
    style: "cute",
    thumbnail: "/templates/baby-shower/elephant-parade.jpg",
    premium: false,
    colors: ["#6B7280", "#93C5FD", "#DBEAFE"],
    fonts: ["Bubblegum Sans", "Nunito"],
    popularity: 89,
    createdAt: "2024-03-20",
  },
  {
    id: "baby-shower-garden-bunny",
    name: "Garden Bunny",
    category: "baby_shower",
    style: "cute",
    thumbnail: "/templates/baby-shower/garden-bunny.jpg",
    premium: true,
    colors: ["#F472B6", "#86EFAC", "#FEF9C3"],
    fonts: ["Quicksand", "Nunito"],
    popularity: 87,
    createdAt: "2024-04-01",
  },
  {
    id: "baby-shower-nautical",
    name: "Nautical Adventure",
    category: "baby_shower",
    style: "themed",
    thumbnail: "/templates/baby-shower/nautical.jpg",
    premium: false,
    colors: ["#1E40AF", "#EF4444", "#FFFFFF"],
    fonts: ["Lobster", "Open Sans"],
    popularity: 84,
    createdAt: "2024-04-10",
  },
  {
    id: "baby-shower-boho-rainbow",
    name: "Boho Rainbow",
    category: "baby_shower",
    style: "bohemian",
    thumbnail: "/templates/baby-shower/boho-rainbow.jpg",
    premium: true,
    colors: ["#B45309", "#059669", "#7C3AED"],
    fonts: ["Amatic SC", "Josefin Sans"],
    popularity: 86,
    createdAt: "2024-04-15",
  },
  {
    id: "baby-shower-storybook",
    name: "Storybook Classic",
    category: "baby_shower",
    style: "vintage",
    thumbnail: "/templates/baby-shower/storybook.jpg",
    premium: false,
    colors: ["#78350F", "#FCD34D", "#FEF3C7"],
    fonts: ["EB Garamond", "Crimson Text"],
    popularity: 83,
    createdAt: "2024-04-20",
  },
  {
    id: "baby-shower-safari",
    name: "Safari Baby",
    category: "baby_shower",
    style: "themed",
    thumbnail: "/templates/baby-shower/safari.jpg",
    premium: true,
    colors: ["#166534", "#CA8A04", "#FEF9C3"],
    fonts: ["Luckiest Guy", "Poppins"],
    popularity: 85,
    createdAt: "2024-05-01",
  },

  // ==========================================
  // BRIDAL SHOWER TEMPLATES (8)
  // ==========================================
  {
    id: "bridal-shower-blush-blooms",
    name: "Blush Blooms",
    category: "bridal_shower",
    style: "romantic",
    thumbnail: "/templates/bridal-shower/blush-blooms.jpg",
    premium: false,
    colors: ["#DB2777", "#FBCFE8", "#FDF2F8"],
    fonts: ["Playfair Display", "Lato"],
    popularity: 94,
    createdAt: "2024-02-01",
  },
  {
    id: "bridal-shower-champagne-toast",
    name: "Champagne Toast",
    category: "bridal_shower",
    style: "elegant",
    thumbnail: "/templates/bridal-shower/champagne-toast.jpg",
    premium: true,
    colors: ["#D4AF37", "#F5F5F4", "#18181B"],
    fonts: ["Cormorant Garamond", "Montserrat"],
    popularity: 91,
    createdAt: "2024-02-15",
  },
  {
    id: "bridal-shower-garden-party",
    name: "Garden Party",
    category: "bridal_shower",
    style: "floral",
    thumbnail: "/templates/bridal-shower/garden-party.jpg",
    premium: false,
    colors: ["#059669", "#F472B6", "#FAFAF9"],
    fonts: ["Dancing Script", "Quicksand"],
    popularity: 89,
    createdAt: "2024-03-01",
  },
  {
    id: "bridal-shower-parisian-chic",
    name: "Parisian Chic",
    category: "bridal_shower",
    style: "classic",
    thumbnail: "/templates/bridal-shower/parisian-chic.jpg",
    premium: true,
    colors: ["#18181B", "#F472B6", "#FAFAF9"],
    fonts: ["Playfair Display", "Didact Gothic"],
    popularity: 88,
    createdAt: "2024-03-10",
  },
  {
    id: "bridal-shower-boho-bride",
    name: "Boho Bride",
    category: "bridal_shower",
    style: "bohemian",
    thumbnail: "/templates/bridal-shower/boho-bride.jpg",
    premium: false,
    colors: ["#B45309", "#78350F", "#FEF3C7"],
    fonts: ["Amatic SC", "Josefin Sans"],
    popularity: 86,
    createdAt: "2024-03-20",
  },
  {
    id: "bridal-shower-tropical-bride",
    name: "Tropical Bride",
    category: "bridal_shower",
    style: "tropical",
    thumbnail: "/templates/bridal-shower/tropical-bride.jpg",
    premium: true,
    colors: ["#059669", "#F472B6", "#FEF9C3"],
    fonts: ["Pacifico", "Poppins"],
    popularity: 84,
    createdAt: "2024-04-01",
  },
  {
    id: "bridal-shower-tea-party",
    name: "Tea Party",
    category: "bridal_shower",
    style: "vintage",
    thumbnail: "/templates/bridal-shower/tea-party.jpg",
    premium: false,
    colors: ["#0D9488", "#FCD34D", "#FEF3C7"],
    fonts: ["EB Garamond", "Lato"],
    popularity: 83,
    createdAt: "2024-04-10",
  },
  {
    id: "bridal-shower-spa-day",
    name: "Spa Day",
    category: "bridal_shower",
    style: "modern",
    thumbnail: "/templates/bridal-shower/spa-day.jpg",
    premium: true,
    colors: ["#5EEAD4", "#FDF4FF", "#18181B"],
    fonts: ["Outfit", "Inter"],
    popularity: 82,
    createdAt: "2024-04-15",
  },

  // ==========================================
  // GRADUATION TEMPLATES (8)
  // ==========================================
  {
    id: "graduation-classic",
    name: "Classic Graduate",
    category: "graduation",
    style: "classic",
    thumbnail: "/templates/graduation/classic.jpg",
    premium: false,
    colors: ["#1E3A8A", "#D4AF37", "#FAFAF9"],
    fonts: ["Playfair Display", "Source Serif Pro"],
    popularity: 95,
    createdAt: "2024-02-01",
  },
  {
    id: "graduation-modern",
    name: "Modern Achievement",
    category: "graduation",
    style: "modern",
    thumbnail: "/templates/graduation/modern.jpg",
    premium: true,
    colors: ["#18181B", "#8B5CF6", "#FFFFFF"],
    fonts: ["Outfit", "Inter"],
    popularity: 91,
    createdAt: "2024-03-01",
  },
  {
    id: "graduation-cap-toss",
    name: "Cap Toss Celebration",
    category: "graduation",
    style: "playful",
    thumbnail: "/templates/graduation/cap-toss.jpg",
    premium: false,
    colors: ["#7C3AED", "#FCD34D", "#FAFAF9"],
    fonts: ["Fredoka One", "Nunito"],
    popularity: 88,
    createdAt: "2024-03-15",
  },
  {
    id: "graduation-school-colors",
    name: "School Spirit",
    category: "graduation",
    style: "bold",
    thumbnail: "/templates/graduation/school-colors.jpg",
    premium: false,
    colors: ["#DC2626", "#18181B", "#FFFFFF"],
    fonts: ["Oswald", "Roboto"],
    popularity: 86,
    createdAt: "2024-04-01",
  },
  {
    id: "graduation-elegant-gold",
    name: "Elegant Gold",
    category: "graduation",
    style: "elegant",
    thumbnail: "/templates/graduation/elegant-gold.jpg",
    premium: true,
    colors: ["#D4AF37", "#18181B", "#FAFAF9"],
    fonts: ["Cinzel", "Lato"],
    popularity: 89,
    createdAt: "2024-04-10",
  },
  {
    id: "graduation-photo-frame",
    name: "Photo Celebration",
    category: "graduation",
    style: "modern",
    thumbnail: "/templates/graduation/photo-frame.jpg",
    premium: true,
    colors: ["#1E40AF", "#FAFAF9", "#18181B"],
    fonts: ["Montserrat", "Open Sans"],
    popularity: 87,
    createdAt: "2024-04-15",
  },
  {
    id: "graduation-confetti",
    name: "Confetti Grad",
    category: "graduation",
    style: "playful",
    thumbnail: "/templates/graduation/confetti.jpg",
    premium: false,
    colors: ["#EC4899", "#8B5CF6", "#06B6D4"],
    fonts: ["Poppins", "Nunito"],
    popularity: 84,
    createdAt: "2024-04-20",
  },
  {
    id: "graduation-minimalist",
    name: "Minimalist Grad",
    category: "graduation",
    style: "minimalist",
    thumbnail: "/templates/graduation/minimalist.jpg",
    premium: false,
    colors: ["#18181B", "#71717A", "#FFFFFF"],
    fonts: ["Inter", "Inter"],
    popularity: 82,
    createdAt: "2024-05-01",
  },

  // ==========================================
  // ANNIVERSARY TEMPLATES (7)
  // ==========================================
  {
    id: "anniversary-golden",
    name: "Golden Anniversary",
    category: "anniversary",
    style: "elegant",
    thumbnail: "/templates/anniversary/golden.jpg",
    premium: true,
    colors: ["#D4AF37", "#18181B", "#FAFAF9"],
    fonts: ["Playfair Display", "Lato"],
    popularity: 93,
    createdAt: "2024-02-14",
  },
  {
    id: "anniversary-silver-elegance",
    name: "Silver Elegance",
    category: "anniversary",
    style: "elegant",
    thumbnail: "/templates/anniversary/silver-elegance.jpg",
    premium: true,
    colors: ["#94A3B8", "#18181B", "#FAFAF9"],
    fonts: ["Cormorant Garamond", "Montserrat"],
    popularity: 89,
    createdAt: "2024-03-01",
  },
  {
    id: "anniversary-romantic-roses",
    name: "Romantic Roses",
    category: "anniversary",
    style: "romantic",
    thumbnail: "/templates/anniversary/romantic-roses.jpg",
    premium: false,
    colors: ["#DC2626", "#FEE2E2", "#FAFAF9"],
    fonts: ["Dancing Script", "Quicksand"],
    popularity: 91,
    createdAt: "2024-03-10",
  },
  {
    id: "anniversary-modern-love",
    name: "Modern Love",
    category: "anniversary",
    style: "modern",
    thumbnail: "/templates/anniversary/modern-love.jpg",
    premium: false,
    colors: ["#EC4899", "#18181B", "#FFFFFF"],
    fonts: ["Outfit", "Inter"],
    popularity: 86,
    createdAt: "2024-03-20",
  },
  {
    id: "anniversary-vintage-photo",
    name: "Vintage Photo",
    category: "anniversary",
    style: "vintage",
    thumbnail: "/templates/anniversary/vintage-photo.jpg",
    premium: true,
    colors: ["#78350F", "#D6D3D1", "#FAFAF9"],
    fonts: ["EB Garamond", "Crimson Text"],
    popularity: 84,
    createdAt: "2024-04-01",
  },
  {
    id: "anniversary-milestone",
    name: "Milestone Celebration",
    category: "anniversary",
    style: "classic",
    thumbnail: "/templates/anniversary/milestone.jpg",
    premium: false,
    colors: ["#1E3A8A", "#D4AF37", "#FAFAF9"],
    fonts: ["Cinzel", "Lato"],
    popularity: 87,
    createdAt: "2024-04-10",
  },
  {
    id: "anniversary-rustic-love",
    name: "Rustic Love Story",
    category: "anniversary",
    style: "rustic",
    thumbnail: "/templates/anniversary/rustic-love.jpg",
    premium: false,
    colors: ["#44403C", "#78350F", "#FEF3C7"],
    fonts: ["Amatic SC", "Josefin Sans"],
    popularity: 82,
    createdAt: "2024-04-15",
  },

  // ==========================================
  // CORPORATE TEMPLATES (8)
  // ==========================================
  {
    id: "corporate-professional",
    name: "Professional",
    category: "corporate",
    style: "classic",
    thumbnail: "/templates/corporate/professional.jpg",
    premium: false,
    colors: ["#1E3A8A", "#64748B", "#FFFFFF"],
    fonts: ["Inter", "Inter"],
    popularity: 92,
    createdAt: "2024-01-30",
  },
  {
    id: "corporate-modern-tech",
    name: "Modern Tech",
    category: "corporate",
    style: "modern",
    thumbnail: "/templates/corporate/modern-tech.jpg",
    premium: true,
    colors: ["#18181B", "#0EA5E9", "#FFFFFF"],
    fonts: ["Outfit", "DM Sans"],
    popularity: 89,
    createdAt: "2024-02-28",
  },
  {
    id: "corporate-gala-event",
    name: "Gala Event",
    category: "corporate",
    style: "elegant",
    thumbnail: "/templates/corporate/gala-event.jpg",
    premium: true,
    colors: ["#D4AF37", "#18181B", "#FAFAF9"],
    fonts: ["Playfair Display", "Lato"],
    popularity: 87,
    createdAt: "2024-03-10",
  },
  {
    id: "corporate-conference",
    name: "Conference Summit",
    category: "corporate",
    style: "bold",
    thumbnail: "/templates/corporate/conference.jpg",
    premium: false,
    colors: ["#7C3AED", "#18181B", "#FFFFFF"],
    fonts: ["Montserrat", "Open Sans"],
    popularity: 86,
    createdAt: "2024-03-20",
  },
  {
    id: "corporate-networking",
    name: "Networking Mixer",
    category: "corporate",
    style: "modern",
    thumbnail: "/templates/corporate/networking.jpg",
    premium: false,
    colors: ["#0D9488", "#18181B", "#FAFAF9"],
    fonts: ["Poppins", "Inter"],
    popularity: 84,
    createdAt: "2024-04-01",
  },
  {
    id: "corporate-product-launch",
    name: "Product Launch",
    category: "corporate",
    style: "bold",
    thumbnail: "/templates/corporate/product-launch.jpg",
    premium: true,
    colors: ["#DC2626", "#18181B", "#FFFFFF"],
    fonts: ["Bebas Neue", "Roboto"],
    popularity: 88,
    createdAt: "2024-04-10",
  },
  {
    id: "corporate-awards",
    name: "Awards Ceremony",
    category: "corporate",
    style: "elegant",
    thumbnail: "/templates/corporate/awards.jpg",
    premium: true,
    colors: ["#D4AF37", "#18181B", "#FAFAF9"],
    fonts: ["Cinzel", "Montserrat"],
    popularity: 85,
    createdAt: "2024-04-15",
  },
  {
    id: "corporate-workshop",
    name: "Workshop Training",
    category: "corporate",
    style: "clean",
    thumbnail: "/templates/corporate/workshop.jpg",
    premium: false,
    colors: ["#2563EB", "#64748B", "#FFFFFF"],
    fonts: ["Inter", "Inter"],
    popularity: 81,
    createdAt: "2024-04-20",
  },

  // ==========================================
  // HOLIDAY TEMPLATES (12)
  // ==========================================
  {
    id: "holiday-christmas-magic",
    name: "Christmas Magic",
    category: "holiday",
    style: "festive",
    thumbnail: "/templates/holiday/christmas-magic.jpg",
    premium: false,
    colors: ["#DC2626", "#15803D", "#D4AF37"],
    fonts: ["Playfair Display", "Nunito"],
    popularity: 98,
    createdAt: "2024-01-10",
  },
  {
    id: "holiday-halloween-spooky",
    name: "Spooky Night",
    category: "holiday",
    style: "playful",
    thumbnail: "/templates/holiday/halloween-spooky.jpg",
    premium: false,
    colors: ["#F97316", "#18181B", "#8B5CF6"],
    fonts: ["Creepster", "Open Sans"],
    popularity: 96,
    createdAt: "2024-01-12",
  },
  {
    id: "holiday-new-year-sparkle",
    name: "New Year Sparkle",
    category: "holiday",
    style: "elegant",
    thumbnail: "/templates/holiday/new-year-sparkle.jpg",
    premium: true,
    colors: ["#D4AF37", "#18181B", "#FAFAF9"],
    fonts: ["Bebas Neue", "Inter"],
    popularity: 95,
    createdAt: "2024-01-05",
  },
  {
    id: "holiday-thanksgiving-harvest",
    name: "Thanksgiving Harvest",
    category: "holiday",
    style: "rustic",
    thumbnail: "/templates/holiday/thanksgiving-harvest.jpg",
    premium: false,
    colors: ["#C2410C", "#CA8A04", "#FEF3C7"],
    fonts: ["Merriweather", "Open Sans"],
    popularity: 91,
    createdAt: "2024-01-15",
  },
  {
    id: "holiday-easter-spring",
    name: "Easter Spring",
    category: "holiday",
    style: "soft",
    thumbnail: "/templates/holiday/easter-spring.jpg",
    premium: false,
    colors: ["#F472B6", "#A3E635", "#FEF9C3"],
    fonts: ["Quicksand", "Nunito"],
    popularity: 88,
    createdAt: "2024-01-18",
  },
  {
    id: "holiday-valentines-love",
    name: "Valentine's Love",
    category: "holiday",
    style: "romantic",
    thumbnail: "/templates/holiday/valentines-love.jpg",
    premium: true,
    colors: ["#DC2626", "#FEE2E2", "#FAFAF9"],
    fonts: ["Dancing Script", "Lato"],
    popularity: 93,
    createdAt: "2024-01-20",
  },
  {
    id: "holiday-4th-july",
    name: "4th of July",
    category: "holiday",
    style: "patriotic",
    thumbnail: "/templates/holiday/4th-july.jpg",
    premium: false,
    colors: ["#DC2626", "#1E40AF", "#FFFFFF"],
    fonts: ["Oswald", "Roboto"],
    popularity: 87,
    createdAt: "2024-01-22",
  },
  {
    id: "holiday-cinco-de-mayo",
    name: "Cinco de Mayo",
    category: "holiday",
    style: "festive",
    thumbnail: "/templates/holiday/cinco-de-mayo.jpg",
    premium: true,
    colors: ["#16A34A", "#DC2626", "#FAFAF9"],
    fonts: ["Lobster", "Open Sans"],
    popularity: 84,
    createdAt: "2024-01-25",
  },
  {
    id: "holiday-st-patricks",
    name: "St. Patrick's Day",
    category: "holiday",
    style: "festive",
    thumbnail: "/templates/holiday/st-patricks.jpg",
    premium: false,
    colors: ["#16A34A", "#D4AF37", "#FAFAF9"],
    fonts: ["Luckiest Guy", "Nunito"],
    popularity: 83,
    createdAt: "2024-01-28",
  },
  {
    id: "holiday-hanukkah",
    name: "Hanukkah Lights",
    category: "holiday",
    style: "elegant",
    thumbnail: "/templates/holiday/hanukkah.jpg",
    premium: true,
    colors: ["#1E40AF", "#D4AF37", "#FAFAF9"],
    fonts: ["Playfair Display", "Lato"],
    popularity: 82,
    createdAt: "2024-02-01",
  },
  {
    id: "holiday-diwali",
    name: "Diwali Festival",
    category: "holiday",
    style: "vibrant",
    thumbnail: "/templates/holiday/diwali.jpg",
    premium: true,
    colors: ["#D97706", "#DC2626", "#FEF3C7"],
    fonts: ["Cinzel", "Poppins"],
    popularity: 86,
    createdAt: "2024-02-05",
  },
  {
    id: "holiday-lunar-new-year",
    name: "Lunar New Year",
    category: "holiday",
    style: "festive",
    thumbnail: "/templates/holiday/lunar-new-year.jpg",
    premium: true,
    colors: ["#DC2626", "#D4AF37", "#FEF2F2"],
    fonts: ["Noto Serif", "Noto Sans"],
    popularity: 89,
    createdAt: "2024-02-08",
  },

  // ==========================================
  // DINNER PARTY TEMPLATES (7)
  // ==========================================
  {
    id: "dinner-elegant-soiree",
    name: "Elegant Soirée",
    category: "dinner_party",
    style: "elegant",
    thumbnail: "/templates/dinner/elegant-soiree.jpg",
    premium: true,
    colors: ["#7C2D12", "#D4AF37", "#FAFAF9"],
    fonts: ["Cormorant Garamond", "Montserrat"],
    popularity: 90,
    createdAt: "2024-02-05",
  },
  {
    id: "dinner-casual-gathering",
    name: "Casual Gathering",
    category: "dinner_party",
    style: "casual",
    thumbnail: "/templates/dinner/casual-gathering.jpg",
    premium: false,
    colors: ["#EA580C", "#14532D", "#FEF3C7"],
    fonts: ["DM Sans", "DM Sans"],
    popularity: 86,
    createdAt: "2024-02-18",
  },
  {
    id: "dinner-wine-tasting",
    name: "Wine Tasting",
    category: "dinner_party",
    style: "elegant",
    thumbnail: "/templates/dinner/wine-tasting.jpg",
    premium: true,
    colors: ["#7F1D1D", "#D4AF37", "#FEF2F2"],
    fonts: ["Playfair Display", "Lato"],
    popularity: 88,
    createdAt: "2024-03-01",
  },
  {
    id: "dinner-bbq-cookout",
    name: "BBQ Cookout",
    category: "dinner_party",
    style: "casual",
    thumbnail: "/templates/dinner/bbq-cookout.jpg",
    premium: false,
    colors: ["#B91C1C", "#CA8A04", "#FEF3C7"],
    fonts: ["Oswald", "Open Sans"],
    popularity: 85,
    createdAt: "2024-03-10",
  },
  {
    id: "dinner-cocktail-hour",
    name: "Cocktail Hour",
    category: "dinner_party",
    style: "modern",
    thumbnail: "/templates/dinner/cocktail-hour.jpg",
    premium: true,
    colors: ["#0D9488", "#18181B", "#FAFAF9"],
    fonts: ["Outfit", "Inter"],
    popularity: 87,
    createdAt: "2024-03-15",
  },
  {
    id: "dinner-garden-party",
    name: "Garden Dinner Party",
    category: "dinner_party",
    style: "floral",
    thumbnail: "/templates/dinner/garden-party.jpg",
    premium: false,
    colors: ["#15803D", "#F472B6", "#F0FDF4"],
    fonts: ["Dancing Script", "Quicksand"],
    popularity: 84,
    createdAt: "2024-03-20",
  },
  {
    id: "dinner-italian-night",
    name: "Italian Night",
    category: "dinner_party",
    style: "themed",
    thumbnail: "/templates/dinner/italian-night.jpg",
    premium: true,
    colors: ["#16A34A", "#DC2626", "#FAFAF9"],
    fonts: ["Lobster", "Poppins"],
    popularity: 83,
    createdAt: "2024-04-01",
  },

  // ==========================================
  // ENGAGEMENT PARTY TEMPLATES (6)
  // ==========================================
  {
    id: "engagement-champagne-dreams",
    name: "Champagne Dreams",
    category: "engagement",
    style: "elegant",
    thumbnail: "/templates/engagement/champagne-dreams.jpg",
    premium: true,
    colors: ["#D4AF37", "#F5F5F4", "#18181B"],
    fonts: ["Playfair Display", "Lato"],
    popularity: 92,
    createdAt: "2024-02-14",
  },
  {
    id: "engagement-love-story",
    name: "Love Story",
    category: "engagement",
    style: "romantic",
    thumbnail: "/templates/engagement/love-story.jpg",
    premium: false,
    colors: ["#EC4899", "#FDF2F8", "#18181B"],
    fonts: ["Dancing Script", "Quicksand"],
    popularity: 89,
    createdAt: "2024-02-20",
  },
  {
    id: "engagement-modern-minimal",
    name: "Modern Minimal",
    category: "engagement",
    style: "minimalist",
    thumbnail: "/templates/engagement/modern-minimal.jpg",
    premium: false,
    colors: ["#18181B", "#71717A", "#FFFFFF"],
    fonts: ["Outfit", "Inter"],
    popularity: 86,
    createdAt: "2024-03-01",
  },
  {
    id: "engagement-rustic-charm",
    name: "Rustic Romance",
    category: "engagement",
    style: "rustic",
    thumbnail: "/templates/engagement/rustic-charm.jpg",
    premium: true,
    colors: ["#78350F", "#A16207", "#FEF3C7"],
    fonts: ["Amatic SC", "Josefin Sans"],
    popularity: 84,
    createdAt: "2024-03-10",
  },
  {
    id: "engagement-garden-romance",
    name: "Garden Romance",
    category: "engagement",
    style: "floral",
    thumbnail: "/templates/engagement/garden-romance.jpg",
    premium: false,
    colors: ["#15803D", "#F472B6", "#FAFAF9"],
    fonts: ["Cormorant Garamond", "Montserrat"],
    popularity: 87,
    createdAt: "2024-03-15",
  },
  {
    id: "engagement-we-said-yes",
    name: "We Said Yes",
    category: "engagement",
    style: "playful",
    thumbnail: "/templates/engagement/we-said-yes.jpg",
    premium: true,
    colors: ["#F472B6", "#FCD34D", "#FAFAF9"],
    fonts: ["Pacifico", "Poppins"],
    popularity: 88,
    createdAt: "2024-03-20",
  },

  // ==========================================
  // HOUSEWARMING TEMPLATES (5)
  // ==========================================
  {
    id: "housewarming-welcome-home",
    name: "Welcome Home",
    category: "housewarming",
    style: "warm",
    thumbnail: "/templates/housewarming/welcome-home.jpg",
    premium: false,
    colors: ["#B45309", "#15803D", "#FEF3C7"],
    fonts: ["Merriweather", "Open Sans"],
    popularity: 88,
    createdAt: "2024-03-01",
  },
  {
    id: "housewarming-modern-keys",
    name: "Modern Keys",
    category: "housewarming",
    style: "modern",
    thumbnail: "/templates/housewarming/modern-keys.jpg",
    premium: true,
    colors: ["#18181B", "#0EA5E9", "#FFFFFF"],
    fonts: ["Outfit", "Inter"],
    popularity: 85,
    createdAt: "2024-03-10",
  },
  {
    id: "housewarming-cozy-cottage",
    name: "Cozy Cottage",
    category: "housewarming",
    style: "rustic",
    thumbnail: "/templates/housewarming/cozy-cottage.jpg",
    premium: false,
    colors: ["#78350F", "#A8A29E", "#FAFAF9"],
    fonts: ["Amatic SC", "Nunito"],
    popularity: 83,
    createdAt: "2024-03-15",
  },
  {
    id: "housewarming-apartment-chic",
    name: "Apartment Chic",
    category: "housewarming",
    style: "minimalist",
    thumbnail: "/templates/housewarming/apartment-chic.jpg",
    premium: true,
    colors: ["#71717A", "#18181B", "#FFFFFF"],
    fonts: ["DM Sans", "Inter"],
    popularity: 81,
    createdAt: "2024-03-20",
  },
  {
    id: "housewarming-garden-home",
    name: "Garden Home",
    category: "housewarming",
    style: "floral",
    thumbnail: "/templates/housewarming/garden-home.jpg",
    premium: false,
    colors: ["#15803D", "#FCD34D", "#F0FDF4"],
    fonts: ["Quicksand", "Nunito"],
    popularity: 82,
    createdAt: "2024-04-01",
  },

  // ==========================================
  // RETIREMENT TEMPLATES (5)
  // ==========================================
  {
    id: "retirement-golden-years",
    name: "Golden Years",
    category: "retirement",
    style: "elegant",
    thumbnail: "/templates/retirement/golden-years.jpg",
    premium: true,
    colors: ["#D4AF37", "#18181B", "#FAFAF9"],
    fonts: ["Playfair Display", "Lato"],
    popularity: 89,
    createdAt: "2024-03-01",
  },
  {
    id: "retirement-beach-sunset",
    name: "Beach Sunset",
    category: "retirement",
    style: "tropical",
    thumbnail: "/templates/retirement/beach-sunset.jpg",
    premium: false,
    colors: ["#F97316", "#0EA5E9", "#FEF3C7"],
    fonts: ["Pacifico", "Poppins"],
    popularity: 86,
    createdAt: "2024-03-10",
  },
  {
    id: "retirement-adventure-awaits",
    name: "Adventure Awaits",
    category: "retirement",
    style: "playful",
    thumbnail: "/templates/retirement/adventure-awaits.jpg",
    premium: true,
    colors: ["#15803D", "#0EA5E9", "#FAFAF9"],
    fonts: ["Fredoka One", "Nunito"],
    popularity: 84,
    createdAt: "2024-03-15",
  },
  {
    id: "retirement-classic-celebration",
    name: "Classic Celebration",
    category: "retirement",
    style: "classic",
    thumbnail: "/templates/retirement/classic-celebration.jpg",
    premium: false,
    colors: ["#1E3A8A", "#D4AF37", "#FAFAF9"],
    fonts: ["Cinzel", "Montserrat"],
    popularity: 87,
    createdAt: "2024-03-20",
  },
  {
    id: "retirement-golf-course",
    name: "Golf Course",
    category: "retirement",
    style: "themed",
    thumbnail: "/templates/retirement/golf-course.jpg",
    premium: true,
    colors: ["#15803D", "#FAFAF9", "#18181B"],
    fonts: ["Oswald", "Open Sans"],
    popularity: 82,
    createdAt: "2024-04-01",
  },

  // ==========================================
  // REUNION TEMPLATES (5)
  // ==========================================
  {
    id: "reunion-family-gathering",
    name: "Family Gathering",
    category: "reunion",
    style: "warm",
    thumbnail: "/templates/reunion/family-gathering.jpg",
    premium: false,
    colors: ["#B45309", "#15803D", "#FEF3C7"],
    fonts: ["Merriweather", "Open Sans"],
    popularity: 90,
    createdAt: "2024-03-01",
  },
  {
    id: "reunion-class-reunion",
    name: "Class Reunion",
    category: "reunion",
    style: "classic",
    thumbnail: "/templates/reunion/class-reunion.jpg",
    premium: true,
    colors: ["#1E3A8A", "#D4AF37", "#FAFAF9"],
    fonts: ["Playfair Display", "Lato"],
    popularity: 88,
    createdAt: "2024-03-10",
  },
  {
    id: "reunion-throwback",
    name: "Throwback Party",
    category: "reunion",
    style: "retro",
    thumbnail: "/templates/reunion/throwback.jpg",
    premium: false,
    colors: ["#F472B6", "#38BDF8", "#FEF9C3"],
    fonts: ["Lobster", "Open Sans"],
    popularity: 85,
    createdAt: "2024-03-15",
  },
  {
    id: "reunion-military",
    name: "Military Reunion",
    category: "reunion",
    style: "formal",
    thumbnail: "/templates/reunion/military.jpg",
    premium: true,
    colors: ["#14532D", "#D4AF37", "#FAFAF9"],
    fonts: ["Cinzel", "Montserrat"],
    popularity: 83,
    createdAt: "2024-03-20",
  },
  {
    id: "reunion-heritage",
    name: "Heritage Celebration",
    category: "reunion",
    style: "elegant",
    thumbnail: "/templates/reunion/heritage.jpg",
    premium: false,
    colors: ["#7C2D12", "#D4AF37", "#FEF3C7"],
    fonts: ["EB Garamond", "Lato"],
    popularity: 84,
    createdAt: "2024-04-01",
  },

  // ==========================================
  // RELIGIOUS TEMPLATES (6)
  // ==========================================
  {
    id: "religious-baptism",
    name: "Baptism Blessing",
    category: "religious",
    style: "soft",
    thumbnail: "/templates/religious/baptism.jpg",
    premium: false,
    colors: ["#DBEAFE", "#D4AF37", "#FAFAF9"],
    fonts: ["Cormorant Garamond", "Lato"],
    popularity: 91,
    createdAt: "2024-03-01",
  },
  {
    id: "religious-first-communion",
    name: "First Communion",
    category: "religious",
    style: "elegant",
    thumbnail: "/templates/religious/first-communion.jpg",
    premium: true,
    colors: ["#D4AF37", "#FAFAF9", "#18181B"],
    fonts: ["Playfair Display", "Montserrat"],
    popularity: 89,
    createdAt: "2024-03-10",
  },
  {
    id: "religious-confirmation",
    name: "Confirmation",
    category: "religious",
    style: "classic",
    thumbnail: "/templates/religious/confirmation.jpg",
    premium: false,
    colors: ["#7C3AED", "#D4AF37", "#FAFAF9"],
    fonts: ["Cinzel", "Lato"],
    popularity: 86,
    createdAt: "2024-03-15",
  },
  {
    id: "religious-bar-mitzvah",
    name: "Bar/Bat Mitzvah",
    category: "religious",
    style: "elegant",
    thumbnail: "/templates/religious/bar-mitzvah.jpg",
    premium: true,
    colors: ["#1E40AF", "#D4AF37", "#FAFAF9"],
    fonts: ["Playfair Display", "Lato"],
    popularity: 88,
    createdAt: "2024-03-20",
  },
  {
    id: "religious-eid-celebration",
    name: "Eid Celebration",
    category: "religious",
    style: "festive",
    thumbnail: "/templates/religious/eid-celebration.jpg",
    premium: true,
    colors: ["#15803D", "#D4AF37", "#FAFAF9"],
    fonts: ["Cinzel", "Poppins"],
    popularity: 87,
    createdAt: "2024-04-01",
  },
  {
    id: "religious-christening",
    name: "Christening",
    category: "religious",
    style: "soft",
    thumbnail: "/templates/religious/christening.jpg",
    premium: false,
    colors: ["#FBCFE8", "#D4AF37", "#FAFAF9"],
    fonts: ["Dancing Script", "Quicksand"],
    popularity: 85,
    createdAt: "2024-04-10",
  },
];

// All available categories
const CATEGORIES = [
  { id: "wedding", name: "Wedding", count: 15 },
  { id: "birthday", name: "Birthday", count: 12 },
  { id: "baby_shower", name: "Baby Shower", count: 10 },
  { id: "bridal_shower", name: "Bridal Shower", count: 8 },
  { id: "graduation", name: "Graduation", count: 8 },
  { id: "anniversary", name: "Anniversary", count: 7 },
  { id: "corporate", name: "Corporate", count: 8 },
  { id: "holiday", name: "Holiday", count: 12 },
  { id: "dinner_party", name: "Dinner Party", count: 7 },
  { id: "engagement", name: "Engagement", count: 6 },
  { id: "housewarming", name: "Housewarming", count: 5 },
  { id: "retirement", name: "Retirement", count: 5 },
  { id: "reunion", name: "Reunion", count: 5 },
  { id: "religious", name: "Religious", count: 6 },
];

export async function GET(request: NextRequest) {
  try {
    const { searchParams } = new URL(request.url);

    // Filter parameters
    const category = searchParams.get("category");
    const style = searchParams.get("style");
    const premium = searchParams.get("premium");
    const search = searchParams.get("search");
    const sort = searchParams.get("sort") || "popularity";
    const page = parseInt(searchParams.get("page") || "1");
    const pageSize = parseInt(searchParams.get("pageSize") || "12");

    let filteredTemplates = [...TEMPLATES];

    // Apply filters
    if (category) {
      filteredTemplates = filteredTemplates.filter(
        (t) => t.category === category
      );
    }

    if (style) {
      filteredTemplates = filteredTemplates.filter((t) => t.style === style);
    }

    if (premium !== null && premium !== undefined) {
      const isPremium = premium === "true";
      filteredTemplates = filteredTemplates.filter(
        (t) => t.premium === isPremium
      );
    }

    if (search) {
      const searchLower = search.toLowerCase();
      filteredTemplates = filteredTemplates.filter(
        (t) =>
          t.name.toLowerCase().includes(searchLower) ||
          t.category.toLowerCase().includes(searchLower) ||
          t.style.toLowerCase().includes(searchLower)
      );
    }

    // Sort
    switch (sort) {
      case "popularity":
        filteredTemplates.sort((a, b) => b.popularity - a.popularity);
        break;
      case "newest":
        filteredTemplates.sort(
          (a, b) =>
            new Date(b.createdAt).getTime() - new Date(a.createdAt).getTime()
        );
        break;
      case "name":
        filteredTemplates.sort((a, b) => a.name.localeCompare(b.name));
        break;
    }

    // Pagination
    const totalCount = filteredTemplates.length;
    const totalPages = Math.ceil(totalCount / pageSize);
    const startIndex = (page - 1) * pageSize;
    const paginatedTemplates = filteredTemplates.slice(
      startIndex,
      startIndex + pageSize
    );

    // Get unique styles for filters
    const styles = [...new Set(TEMPLATES.map((t) => t.style))];

    return NextResponse.json({
      success: true,
      data: {
        templates: paginatedTemplates,
        filters: {
          categories: CATEGORIES,
          styles,
        },
      },
      meta: {
        page,
        pageSize,
        totalCount,
        totalPages,
        totalTemplates: TEMPLATES.length,
      },
    });
  } catch (error) {
    console.error("Templates API error:", error);
    return NextResponse.json(
      {
        success: false,
        error: { code: "SERVER_ERROR", message: "Failed to fetch templates" },
      },
      { status: 500 }
    );
  }
}
